Chore/4624 test blotter
AdaptiveConsulting/ReactiveTraderCloud pull request #2154
Opened 2023-02-08 22:35 UTC by Clark-Adaptive

2023-02-09 14:06 UTC, joeg-adaptive submitted a review, later dismissed

2023-02-16 15:39 UTC, joeg-adaptive submitted a review, later dismissed

2023-02-24 18:53 UTC, iprado78 requested changes

2023-02-24 18:53 UTC, iprado78 commented on src/client/e2e/blotter.spec.ts
> +    const firstTradeID = await blotterPage
just for a little more clarity, call it `firstRowTradeID`

2023-02-24 18:53 UTC, iprado78 commented on src/client/e2e/blotter.spec.ts
> +    const firstTradeID = await blotterPage
```
await blotterPage.locator('[role="grid"] > tr')
  .nth(0)
  .locator('td')
  .nth(getTradeIdColIndex())
  .textContent()
```

This makes explicit that you are first selecting the first row, then the trade id cell in it.

2023-02-24 18:53 UTC, iprado78 commented on src/client/e2e/blotter.spec.ts
> +    const sortTradeID = await blotterPage.getByText("Trade ID", { exact: true })
again, clearer if it's `tradeIDColHeader` - let's me visualize it like a user

2023-02-24 18:53 UTC, iprado78 commented on src/client/e2e/blotter.spec.ts
> +      .locator('[role="grid"] > tr > td')
pattern/function

2023-02-24 18:53 UTC, iprado78 commented on src/client/e2e/blotter.spec.ts
> +    const searchedRow = "1"
`const tradeIDToSearch = ...  // Name change for clarity`

2023-02-24 18:53 UTC, iprado78 commented on src/client/e2e/blotter.spec.ts
> +    const tradeIDColHeader = await blotterPage.getByText("Trade ID", {
good name!

2023-02-24 18:53 UTC, iprado78 commented on src/client/e2e/blotter.spec.ts
> +    const searchedRow = "2"
as above: `const tradeIDToSearch``

2023-02-24 18:53 UTC, iprado78 commented on src/client/e2e/blotter.spec.ts
> +      const data = fs
don't need intermediate variable, `filteredCSVRows = `

2023-02-24 21:11 UTC, iprado78 approved these changes

2023-02-24 21:13 UTC, merged